ALTER TABLE users
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(1024) DEFAULT '';
